[theme]
base = "light"
primaryColor = "#F6B73C"
backgroundColor = "#7f8690"
secondaryBackgroundColor = "#565252"
textColor = "#0B1F33"
font = "sans-serif"

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
